# Generated by Django 5.2.7 on 2025-10-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
    ]
