# Generated by Django 5.2.7 on 2025-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
